// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWZvLGm8UIvJeB-2OoJ55s5dPlLtVnFcw',
    appId: '1:989551866193:web:8956d7f02d177b93616370',
    messagingSenderId: '989551866193',
    projectId: 'flatmatev4',
    authDomain: 'flatmatev4.firebaseapp.com',
    storageBucket: 'flatmatev4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoyyZIF3Dc1xN_ltaqR2mH260HoBcFV6M',
    appId: '1:989551866193:android:b5238c4ee741e677616370',
    messagingSenderId: '989551866193',
    projectId: 'flatmatev4',
    storageBucket: 'flatmatev4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNOOPHh88cQBHPwhKkG2IG_c2y4E9cj4I',
    appId: '1:989551866193:ios:1ed6b21b1b411582616370',
    messagingSenderId: '989551866193',
    projectId: 'flatmatev4',
    storageBucket: 'flatmatev4.firebasestorage.app',
    iosBundleId: 'com.example.flatmateAppV3',
  );

}